apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-app-ingress
  annotations:
    ingress.vk.cloud/load-balancer-type: "standard"
spec:
  rules:
    - host: demo-app.89-208-86-40.com  # Замените на ваш домен
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-app-service
                port:
                  number: 80